---
defaults: &defaults
  application_name: 'demo-app'
  sprop_mappings:
    user_id: 'prop12'
    page_name: 'prop82'
    site_name: 'prop26'
    session_id: 'prop37'
    timestamp: 'prop98'
production:
  account: 'proddemoapp'
  enabled: true
  <<: *defaults
development:
  account: 'devdemoapp'
  enabled: true
  <<: *defaults
test:
  account: 'testdemoapp'
  enabled: true
  <<: *defaults
